name: intellifold
channels:
  - conda-forge
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - python=3.11
  - mmseqs2=13.45111=h95f258a_1
  - pip
  - pip:
      - rdkit==2024.3.2
      - torch==2.6.0
      - accelerate==1.1.1
      - deepspeed==0.16.4
      - biopython==1.85
      - numpy==1.24.0
      - pandas==2.2.3
      - scipy==1.14.1
      - networkx==3.4.2
      - numba==0.61.0
      - einops==0.8.0
      - einx==0.3.0
      - ml-collections==1.0.0
      - torchdiffeq==0.2.5
      - mashumaro==3.14
      - pyyaml==6.0.2
      - tqdm==4.67.1
      - click==8.1.8
      - ihm==2.5
      - modelcif==1.2
      - fsspec==2025.3.0
      - -i https://pypi.tuna.tsinghua.edu.cn/simple
